build: 
	javac -cp "./libs/*" Populate.java
test:
	java -cp "./:libs/ojdbc6.jar" Populate hetrec2011-movielens-2k-v2/user_ratedmovies-timestamps.dat

run:
	java -cp "./:libs/ojdbc6.jar"\
	 Populate hetrec2011-movielens-2k-v2/tags.dat \
	 hetrec2011-movielens-2k-v2/movies.dat \
	 hetrec2011-movielens-2k-v2/movie_genres.dat \
	 hetrec2011-movielens-2k-v2/movie_directors.dat \
	 hetrec2011-movielens-2k-v2/movie_countries.dat \
	 hetrec2011-movielens-2k-v2/movie_actors.dat \
	 hetrec2011-movielens-2k-v2/movie_locations.dat \
	 hetrec2011-movielens-2k-v2/movie_tags.dat \
	 hetrec2011-movielens-2k-v2/user_ratedmovies-timestamps.dat \
	 hetrec2011-movielens-2k-v2/user_taggedmovies-timestamps.dat
 
#hetrec2011-movielens-2k-v2/user_ratedmovies.dat \
#hetrec2011-movielens-2k-v2/user_taggedmovies.dat \
